name: "Deploy NuGet Package"

on:
  push:
    tags:
      - v*

env:
  PROJECT_PATH: "HardwareHero.Filter/HardwareHero.Filter.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  deploy:
    name: "Deploy"
    runs-on: windows-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install dotnet"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.x"

      - name: "Restore packages"
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: "Build project"
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

      - name: "Get version"
        id: version
        uses: Im-Fran/version-from-tag-action@v1.0.3
        with:
          remove-first-character: "v"
          version-variable-name: "VERSION"

      - name: "Pack project"
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -p:PackageVersion=${{ env.VERSION }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: "Push package"
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
